### ISSUE TITLE
3주차 발표 역할 분담

### ISSUE THREAD

**Issue by Jung-kr** [Sfarm18/Sfarm#1]
## 목적
> 산학프로젝트 3주차 발표

## 작업 상세 내용
> 역할분담
발표: 정우용
ppt 제작: 이겨레

## 참고 사항
> ppt 제작 후 전송 바람

**Comment by Lee-Gyeore** [comment]
보냈으니 검토 바람

**Comment by Jung-kr** [comment]
확인 완료
