### ISSUE TITLE
프론트 myfarm 페이지 관련 결정사항

### ISSUE THREAD

**Issue by Lee-Gyeore** [Sfarm18/Sfarm#13]
## 목적
>my farm 페이지 개수 결정
## 작업 상세 내용
>기존 틀에는 myfarm이 하나로 되어있음.
myfarm에 총 3페이지가 필요해 네비게이션 바 경로 바꿔야 함.
결정 바람

## 참고 사항
>

**Comment by Jung-kr** [comment]
컴포넌트 3개를 만들고 Myfarm bar 클릭시 Weather 컴포넌트가 가장 먼저 뜨게 개발하면 됨
