### ISSUE TITLE
중간 발표

### ISSUE THREAD

**Issue by Lee-Gyeore** [Sfarm18/Sfarm#17]
## 목적
>중간 발표 의견 공유
## 작업 상세 내용
>중간 발표 ppt 공유, 의견 공유
## 참고 사항
>

**Comment by Lee-Gyeore** [comment]
[산학 프로젝트 Sfarm 중간발표 초안.pptx](https://github.com/Sfarm18/Sfarm/files/9802844/Sfarm.pptx)

**Comment by Lee-Gyeore** [comment]
확인 후 수정해야 할 부분 알려줘

**Comment by Lee-Gyeore** [comment]
수정본
[Sfarm.pptx](https://github.com/Sfarm18/Sfarm/files/9843959/Sfarm.pptx)

**Comment by Jung-kr** [comment]
[Sfarm (1).pptx](https://github.com/Sfarm18/Sfarm/files/9844171/Sfarm.1.pptx)

구현방향 부분 수정

**Comment by Lee-Gyeore** [comment]
최종
[Sfarm.pptx](https://github.com/Sfarm18/Sfarm/files/9844198/Sfarm.pptx)
