### ISSUE TITLE
요구사항정의서

### ISSUE THREAD

**Issue by Lee-Gyeore** [Sfarm18/Sfarm#2]
## 목적
>요구 사항 정의서 공유
## 작업 상세 내용
>추후 요구 사항 정의서 제출 전까지 최신화
## 참고 사항
>-

**Comment by Lee-Gyeore** [comment]
[Sfarm 요구사항 정의서.docx](https://github.com/Sfarm18/Sfarm/files/9652275/Sfarm.docx)

초안

**Comment by Jung-kr** [comment]
[Sfarm 요구사항 정의서.docx](https://github.com/Sfarm18/Sfarm/files/9836151/Sfarm.docx)

수정할 부분 확인 바랍니다

**Comment by Lee-Gyeore** [comment]
수정할 것들
4페이지 1.2.1, 1.2.2 크롤링->날씨 api사용해 불러온다.
5페이지 1.2.2 (3) YOLO 제거
7페이지 FF2.1.2 직물 ->작물
7페이지 CF1. 사용자의 CCTV를 .->사용자의 CCTV로 
7페이지 WF1. 크롤링 -> 날씨 api
8페이지 SR1. (이름, 휴대폰 번호 등)->(아이디, 비밀번호, 이름, 휴대폰 번호, 주소, 이메일)  '등' 제거(모호성)
9페이지 IIF UIF1. 시스템은 웹 기반으로 사용하도록 하되 안드로이드에서도 몇몇 기능이 지원된다.->어떤 기능 지원하는지
ex) 로그인, 날씨정보, 야생동물 출몰 기록, 야생동물 출몰 알림,
