### ISSUE TITLE
MyFarm 페이지 path 관련

### ISSUE THREAD

**Issue by Jung-kr** [Sfarm18/Sfarm#20]
## 목적
> MyFarm 페이지 path 수정
## 작업 상세 내용
> /MyFarmCCTV -> /myfarm/CCTV
/MyFarmBoard - > /myfarm/board
/MyFarmRecord -> /myfarm/record
## 참고 사항
> 수정 완료 후 코멘트 달겠음

**Comment by Jung-kr** [comment]
수정 완료

**Comment by Lee-Gyeore** [comment]
확인
