### ISSUE TITLE
리액트 폴더 구조 관련

### ISSUE THREAD

**Issue by Jung-kr** [Sfarm18/Sfarm#22]
## 목적
> 리액트 폴더 구조 수정
## 작업 상세 내용
> assets -> 서비스에서 사용하는 font들과 image들을 정의
apis -> 서비스에서 제공하는 기능들에 대해 백엔드와 소통하는 api구조
components -> 서비스에서 사용하는 component들을 정의
pages -> 만들어 둔 component들의 feature들을 모아 페이지를 구성
libs -> 공통으로 사용하는 함수
## 참고 사항
> image 파일 경로 변경했는데 About.js와 Slidebanner.js에 적용이 안됨. 확인바람

**Comment by Lee-Gyeore** [comment]
기존 public파일에서 가져오던 방식에서는 해당 코드에서 불러오는 방식.
asset파일에서 가져오는 방식으로 바뀌어서 경로 import해오는 방식으로 변경함
