### ISSUE TITLE
발명설명서 ppt 공유

### ISSUE THREAD

**Issue by Lee-Gyeore** [Sfarm18/Sfarm#25]
## 목적
>발명설명서 발표용 ppt 공유
## 작업 상세 내용
>ppt 내용 피드백 및 수정
## 참고 사항
>

**Comment by Lee-Gyeore** [comment]
[Sfarm 발명설명서.pptx](https://github.com/Sfarm18/Sfarm/files/10042928/Sfarm.pptx)

-국립 공원 연구원 자료 캡쳐해서 넣어 달라는 부분이 기억이 안 나서 일단 만듦.
-검토 후 ppt 수정할 내용 공유해 주면 수정해서 올리겠음.

**Comment by Jung-kr** [comment]
6페이지 농업인 커뮤니티 구성 삭제
7페이지 각 선행기술에 해당하는 자료 추가
8페이지 농가피해감소 삭제

**Comment by Lee-Gyeore** [comment]
[Sfarm 발명설명서.pptx](https://github.com/Sfarm18/Sfarm/files/10049788/Sfarm.pptx)

수정본
