### ISSUE TITLE
발명설명서 공유

### ISSUE THREAD

**Issue by Jung-kr** [Sfarm18/Sfarm#26]
## 목적
> 발명설명서 공유
## 작업 상세 내용
> 발명설명서 수정 및 검토
## 참고 사항
>
[발명설명서.docx](https://github.com/Sfarm18/Sfarm/files/10031836/default.docx)

**Comment by Lee-Gyeore** [comment]
발명 용도에 퍼센트가 인원수가 아니라 가구수였음
![image](https://user-images.githubusercontent.com/85282633/202749084-1b88aeb8-4fd4-46d1-9174-b9943c04f9bb.png)
