### ISSUE TITLE
Peer-Review 발표 자료 관련 토의

### ISSUE THREAD

**Issue by Lee-Gyeore** [Sfarm18/Sfarm#29]
## 목적
>Peer-Review 발표 자료 관련 토의
## 작업 상세 내용
>리뷰에 따른 코멘트 협의
## 참고 사항
>

**Comment by Jung-kr** [comment]
[Sfarm 코멘트 - 답.docx](https://github.com/Sfarm18/Sfarm/files/10096571/Sfarm.-.docx)

**Comment by Lee-Gyeore** [comment]
[Sfarm 코멘트 - 답.docx](https://github.com/Sfarm18/Sfarm/files/10096658/Sfarm.-.docx)
-cnn관련 추가
-problem 관련 코멘트:  "유해 조수를 포함한 대응 가능한 피해 줄이는 것을 목표" 로 포커스 잡는게 나을 듯

**Comment by Lee-Gyeore** [comment]
[Sfarm PR.pptx](https://github.com/Sfarm18/Sfarm/files/10096682/Sfarm.PR.pptx)
수정 하고 싶은 부분 알려줘

**Comment by Lee-Gyeore** [comment]
[Sfarm PR.pptx](https://github.com/Sfarm18/Sfarm/files/10098605/Sfarm.PR.pptx)
