### ISSUE TITLE
4주차 멘토링 결과 공유

### ISSUE THREAD

**Issue by Lee-Gyeore** [Sfarm18/Sfarm#3]
## 목적
>4주차 멘토링 결과 공유
## 작업 상세 내용
>멘토링 후 멘토님이 메일로 보내주신 내용 공유
## 참고 사항
>

**Comment by Jung-kr** [comment]
1. 한글파일로 되어진 내용을 좀더 구체적이고 디테일하게 작성하시고 
그파일을 엑셀로 정리해 주세요 (굉장히 중요합니다.)

2. 그리고 제가 찾은것 중에 최근에 국립공원에서 카메라 이미지처리 기술로 야생동물인식 시스템을 만들어 국립공원에서 사용하고 있는 내용을 첨부파일로 보내드립니다.(PDF 참고 하시면 됩니다.) 

3. 그리고 이미지 처리 기술은 조금만 검색하면 많이 나오니 참조해주세요
https://yunwoong.tistory.com/86
https://steemit.com/kr/@codingart/6-8-opencv-catface
[요구사항정의서_샘플.xlsx](https://github.com/Sfarm18/Sfarm/files/9652303/_.xlsx)
[NPRI 2020-45 야생동물 영상인식 딥러닝 소프트웨어 개발 연구(1차년도).pdf](https://github.com/Sfarm18/Sfarm/files/9652304/NPRI.2020-45.1.pdf)
