### ISSUE TITLE
11/28 역할분담

### ISSUE THREAD

**Issue by Jung-kr** [Sfarm18/Sfarm#31]
## 목적
> 11/28 역할분담
## 작업 상세 내용
> 우용 - (backend) 회원가입, 로그인, 로그아웃
겨레 - (front) 메인페이지, 슬라이드배너 그림 삽입, About 설명, axios 알아보기
## 참고 사항
> 11/29일은 회원가입 프론트 연동 및 프론트 수정 예정

**Comment by Lee-Gyeore** [comment]
확인

**Comment by Lee-Gyeore** [comment]
메인 완성
슬라이드배너 그림 삽입만 함
어바웃 설명 작성 완료
