### ISSUE TITLE
웹 사진 공유

### ISSUE THREAD

**Issue by Lee-Gyeore** [Sfarm18/Sfarm#32]
## 목적
>웹페이지에 사용될 사진 공유
## 작업 상세 내용
>슬라이드배너, 메인페이지 사진
## 참고 사항
>

**Comment by Jung-kr** [comment]
![9_color_tree_design_vector_by_freeiconsdownload_dcx15ud-removebg-preview](https://user-images.githubusercontent.com/81340804/204301398-e13b4082-75a7-4d81-a767-03ececcd76e7.png)
![푸른_나무_일러스트__나무_클립_아트_Png__큰_나무__초록_PNG_일러스트_및_PSD_이미지_무료_다운로드_-_Pngtree-removebg-preview](https://user-images.githubusercontent.com/81340804/204301424-639f70d7-2348-45e3-929e-71b7ed1439d1.png)
