### ISSUE TITLE
4주차 멘토링 중 작성된 면담 내용 공유 바랍니다

### ISSUE THREAD

**Issue by Jung-kr** [Sfarm18/Sfarm#4]
## 목적
> 멘토 일지 작성
## 작업 상세 내용
> 멘토링 면담 내용
## 참고 사항
> -

**Comment by Lee-Gyeore** [comment]
질문 내용
-야생동물 사진 데이터 수집 관련 방법
-날씨 데이터 크롤링 애로사항
-문서 개선점

면담 결과
-스마트 농장 관리 아이디어 긍정적
-야생동물 사진 데이터셋 수집 관련 방법 이메일 공유 예정
-기상청에서 날씨 크롤링 가능한지 미리 확인 해야 할 것
-요구사항 분석서 엑셀로 작성하여 한눈에 보기 용이하게 작성하는 것이 좋을것

기타
요구 사항 분석서를 한글 파일에 서술형으로 작성 시에는 보고서 제출 용도로는 좋지만 실제로 다 인원 작업에는 불편함. 따라서 간결하게 엑셀 파일로 기능 별로 정리하는 것이 바람직.
