### ISSUE TITLE
크롤링이미지 공유

### ISSUE THREAD

**Issue by Lee-Gyeore** [Sfarm18/Sfarm#42]
## 목적
>크롤링 이미지 공유
## 작업 상세 내용
>
## 참고 사항
>
[wildboar.zip](https://github.com/Sfarm18/Sfarm/files/10163946/wildboar.zip)

**Comment by Jung-kr** [comment]
[wildboar.zip](https://github.com/Sfarm18/Sfarm/files/10164055/wildboar.zip)
wildboar 아닌 이미지 삭제

**Comment by Lee-Gyeore** [comment]
[waterdeer.zip](https://github.com/Sfarm18/Sfarm/files/10164093/waterdeer.zip)

**Comment by Lee-Gyeore** [comment]
[person.zip](https://github.com/Sfarm18/Sfarm/files/10164143/person.zip)

**Comment by Jung-kr** [comment]
[person.zip](https://github.com/Sfarm18/Sfarm/files/10164298/person.zip)
[waterdeer.zip](https://github.com/Sfarm18/Sfarm/files/10164299/waterdeer.zip)
