### ISSUE TITLE
시연 영상 관련 회의

### ISSUE THREAD

**Issue by Lee-Gyeore** [Sfarm18/Sfarm#62]
## 목적
>시연 영상 관련 회의 결과 공유
## 작업 상세 내용
>
-파이썬 모델 영상
-웹 영상

**Comment by Lee-Gyeore** [comment]
-파이썬 모델 : 유튜브 영상 활용해 모델 시연 영상 촬영 
(사람, 멧돼지)

**Comment by Jung-kr** [comment]
모델 연동이 안되었기 때문에 웹 시연 영상 촬영 이후 모델 시연 영상을 따로 촬영할 예정
